# Generated by Django 6.0.3 on 2026-04-26 15:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_created_at'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questionvote',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='questionvote',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questionvote',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-name'], 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время создания'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время создания'),
        ),
        migrations.CreateModel(
            name='AnswerLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время создания')),
                ('value', models.SmallIntegerField(choices=[(1, 'Лайк'), (-1, 'Дизлайк')], default=1)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='questions.answer', verbose_name='Ответ')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_votes', to='core.profile', verbose_name='Автор лайка')),
            ],
            options={
                'verbose_name': 'Лайк ответа',
                'verbose_name_plural': 'Лайки ответов',
                'ordering': ['-created_at'],
                'abstract': False,
                'unique_together': {('user', 'answer')},
            },
        ),
        migrations.CreateModel(
            name='QuestionLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время создания')),
                ('value', models.SmallIntegerField(choices=[(1, 'Лайк'), (-1, 'Дизлайк')], default=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='questions.question', verbose_name='Вопрос')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_votes', to='core.profile', verbose_name='Автор лайка')),
            ],
            options={
                'verbose_name': 'Лайк вопроса',
                'verbose_name_plural': 'Лайки вопросов',
                'ordering': ['-created_at'],
                'abstract': False,
                'unique_together': {('user', 'question')},
            },
        ),
        migrations.DeleteModel(
            name='AnswerVote',
        ),
        migrations.DeleteModel(
            name='QuestionVote',
        ),
    ]
