# Generated by Django 6.0.3 on 2026-05-25 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_remove_question_question_fts_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='question',
            name='question_fts_idx',
        ),
        migrations.RemoveField(
            model_name='question',
            name='search_vector',
        ),
    ]
