# Generated by Django 6.0.3 on 2026-05-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_profile_bio'),
        ('questions', '0003_answer_rating_question_answers_count_question_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Правильный?'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answers_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во ответов'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=25, unique=True, verbose_name='Имя тега'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(condition=models.Q(('is_correct', True)), fields=('question',), name='unique_correct_answer_per_question'),
        ),
    ]
