# Generated by Django 6.0.3 on 2026-05-11 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_alter_question_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='questions_count',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Кол-во вопросов'),
        ),
    ]
