# Generated by Django 6.0.3 on 2026-05-12 10:03

import questions.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_alter_question_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(related_name='questions', to='questions.tag', validators=[questions.validators.validate_tags_count], verbose_name='Теги вопроса'),
        ),
    ]
