# Generated by Django 6.0.3 on 2026-05-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_alter_question_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(related_name='questions', to='questions.tag', verbose_name='Теги вопроса'),
        ),
    ]
