services:
  x-django-base: &django-base
    build: .
    env_file:
    - .env.docker
    volumes:
    - .:/app
    - django_media:/app/media
    networks:
    - app_network
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
  db:
    image: postgres:17
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.docker
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  redis:
    image: redis:7-alpine
    container_name: redis_broker
    ports:
      - "6379:6379"
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  web:
    <<: *django-base
    container_name: web_app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"

  celery:
    <<: *django-base
    container_name: celery_worker
    # Запуск воркера. application - это папка, где лежит твой celery.py
    command: celery -A application worker -l INFO

  celery-beat:
    <<: *django-base
    container_name: celery_beat
    command: celery -A application beat -l INFO

networks:
  app_network:
    driver: bridge

volumes:
  django_media:
  postgres_data:
