services:
  db:
    image: postgres:17
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.docker
    environment:
      POSTGRES_DB: ${DB_NAME:-vk_edu_web_paronko_d_db}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres_password}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: web_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./media:/app/media
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.docker
    environment:
      - ENV_FILE=.env.docker
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  django_media:
  postgres_data:
