# Generated by Django 6.0.3 on 2026-05-11 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='correct_answers_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во правильных ответов'),
        ),
    ]
