# Generated by Django 6.0.3 on 2026-05-25 11:40

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('questions', '0003_remove_question_question_fts_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='search_vector',
            field=models.GeneratedField(db_persist=True, expression=django.contrib.postgres.search.SearchVector('title', 'content', config='simple'), output_field=django.contrib.postgres.search.SearchVectorField()),
        ),
        migrations.AddIndex(
            model_name='question',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='question_fts_idx'),
        ),
    ]
